#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# train_linux_fieldprism.py
#
# CUDA 12.1 ===> pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 --index-url https://download.pytorch.org/whl/cu121
# CUDA 12.6 ===> pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu126
#
# REQUIRED MULTI-GPU LAUNCH COMMAND (NCCL stability on this machine):
#   export NCCL_P2P_DISABLE=1
#   export NCCL_IB_DISABLE=1
#   export NCCL_ASYNC_ERROR_HANDLING=1
#   export NCCL_DEBUG=INFO
#   YOLO_DEVICE='0,1' \
#   /home/brlab/Dropbox/TextCollage/.venv_TC_linux/bin/python \
#   /home/brlab/Dropbox/TextCollage/train_linux_fieldprism.py

"""
FieldPrism Ruler Detector — YOLOv12 Training

Trains YOLOv12 nano and/or xlarge models for single-class (ruler) detection
on the FieldPrism-augmented dataset generated by GenerateFieldPrismTrainingImages.py.

Dataset: /datac/FieldPrism_YOLO_Training_Data/data.yaml
         nc=1, names=['ruler']

REQUIRED LAUNCH COMMAND (multi-GPU DDP on RTX 6000 Ada):

export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
export NCCL_ASYNC_ERROR_HANDLING=1
export NCCL_DEBUG=INFO
YOLO_DEVICE='0,1' python train_linux_fieldprism.py
"""

from ultralytics import YOLO
import os
import wandb

from train_utils import evaluate_and_log
from ExportCollage import ExportCollage

# ─── Configuration ────────────────────────────────────────────────────────────

DATA_YAML = "/datac/FieldPrism_YOLO_Training_Data/data.yaml"

WANDB_PROJECT = "FieldPrism_YOLO12"
RUN_PREFIX = "fieldprism_ruler"

# Set to: "n" (nano), "x" (xlarge), or "both"
TRAIN_VARIANT = "both"

# ─── Multi-GPU ────────────────────────────────────────────────────────────────

DEVICE = os.environ.get("YOLO_DEVICE", "0,1")
EXPORT_DEVICE = os.environ.get("YOLO_EXPORT_DEVICE", "0")

# Batch sizing (global batch, must be multiple of GPU count = 2)
BATCH_N = 224
BATCH_X = 42

IMGSZ = 640
EPOCHS = 300
SEED = 2025


if __name__ == '__main__':
    import torch

    if not os.path.exists(DATA_YAML):
        raise FileNotFoundError(
            f"Dataset not found at {DATA_YAML}. "
            "Run GenerateFieldPrismTrainingImages.py first."
        )

    try:
        torch.multiprocessing.set_start_method("spawn", force=True)
    except RuntimeError:
        pass
    os.environ.setdefault("OMP_NUM_THREADS", "1")
    os.environ.setdefault("MKL_NUM_THREADS", "1")

    # ── W&B environment ───────────────────────────────────────────────────
    os.environ["WANDB_MODE"] = "online"
    os.environ["WANDB_PROJECT"] = WANDB_PROJECT

    trained_models = {}

    # ── Train YOLOv12n ────────────────────────────────────────────────────
    if TRAIN_VARIANT in ("n", "both"):
        RUN_NAME = f"{RUN_PREFIX}_yolo12n"
        wandb.init(project=WANDB_PROJECT, name=RUN_NAME)

        model = YOLO("yolov12/yolov12n.pt")
        results = model.train(
            data=DATA_YAML,
            epochs=EPOCHS,
            batch=BATCH_N,
            workers=32,
            imgsz=IMGSZ,
            device=DEVICE,
            name=RUN_NAME,
            seed=SEED,
            patience=100,

            val=True,
            cache="ram",
            deterministic=True,
            exist_ok=False,
        )

        best_n = f"runs/detect/{RUN_NAME}/weights/best.pt"
        ExportCollage(
            weights=best_n,
            prefix=RUN_NAME,
            imgsz=IMGSZ,
        ).export(["coreml", "ncnn", "openvino", "torchscript", "onnx"])
        wandb.finish()
        trained_models["yolo12n"] = best_n
        print("YOLOv12n training finished successfully.")

    # ── Train YOLOv12x ────────────────────────────────────────────────────
    if TRAIN_VARIANT in ("x", "both"):
        RUN_NAME = f"{RUN_PREFIX}_yolo12x"
        wandb.init(project=WANDB_PROJECT, name=RUN_NAME)

        modelx = YOLO("yolov12/yolov12x.pt")
        resultsx = modelx.train(
            data=DATA_YAML,
            epochs=EPOCHS,
            batch=BATCH_X,
            workers=32,
            imgsz=IMGSZ,
            device=DEVICE,
            name=RUN_NAME,
            seed=SEED,
            patience=100,

            val=True,
            cache="ram",
            deterministic=True,
            exist_ok=False,
        )

        best_x = f"runs/detect/{RUN_NAME}/weights/best.pt"
        ExportCollage(
            weights=best_x,
            prefix=RUN_NAME,
            imgsz=IMGSZ,
        ).export(["coreml", "ncnn", "openvino", "torchscript", "onnx"])
        wandb.finish()
        trained_models["yolo12x"] = best_x
        print("YOLOv12x training finished successfully.")

    # ── Evaluate on test split ────────────────────────────────────────────
    if trained_models:
        evaluate_and_log(
            models=trained_models,
            data_yamls={"FieldPrism": DATA_YAML},
            device=DEVICE,
            imgsz=IMGSZ,
            out_dir="/datac/FieldPrism_YOLO_Training_Data/eval",
            wandb_project="FieldPrism-YOLO12-Evals",
            extra_config={"host": "ubuntu22", "notes": "fieldprism ruler test-split evaluation"},
        )
